apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }} 
        resources:
        {{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.containerPort }} 
        livenessProbe:
          httpGet:
          {{ toYaml .Values.resources.livenessProbe | indent 12 }}
        readinessProbe:
          httpGet:
          {{ toYaml .Values.resources.readinessProbe | indent 12 }}