apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
spec:
  selector:
    app: techtrends 
  ports:
  - port: 4111
    targetPort: 3111 
    protocol: TCP
  type: ClusterIP